### PR TITLE
Add modo costs and tests

### PR DESCRIPTION
**Pull request by wachunga**
I _think_ I have modo's costs captured correctly. Tried to do it with config that will work for Evo and car2go as well.

### CODE REVIEW

**Comment by canadianveggie** [comment]
I think you're better off flattening the packages into the top-level entity and having multiple Modo configs.
It will make things simpler when you try to encode the car2go rates (which are a lot more complicated now with packages and 2 different car types): https://www.car2go.com/CA/en/vancouver/rates/

I'm thinking every top-level config has a bunch of metadata (company, passengers, description, city, currency, etc) which can be filtered on, and rates - time, distance, fees. It will be some copy-paste for the various packages each company has, but I think it simplifies the code.

The default calcDefaultCost method should calculate the costs for all packages and sort them.

So when you say, I want a car for 4 hours and to drive 30 km, it says here are your options:
Modo - Monthly - Daily Drives - $15.25
Car2Go - smart - 3 hours - $17.50
Evo - $18.00
Car2Go - Mercedes-Benz - 3 hours - $19.25
Car2Go - smart - 6 hours - $20.00
Modo - Monthly - Large and Loadable - $21.25
...

If you need a >= 4 passenger vehicle, it can filter out the ones that don't match.

**Comment by wachunga** [comment]
Thanks for the review.

> I think you're better off flattening the packages into the top-level entity and having multiple Modo configs.
> It will make things simpler when you try to encode the car2go rates (which are a lot more complicated now with packages and 2 different car types): https://www.car2go.com/CA/en/vancouver/rates/

I'm not so sure about flattening completely. This is what I had as a draft for car2go:
```js

const car2go = {
  key: "car2go-yvr",
  url: "https://www.car2go.com/CA/en/vancouver/rates/",
  lastUpdate: '2019-06-15',
  currency: "CAD",
  fees: {
    trip: 1, // first 200 trips per calendar year
    registration: 5,
    annual: 2,
    daily: 1.5 // tax on trips lasting 8 hours or more
  },
  packages: [
    {
      name: "minute rate - smart",
      vehicle: "smart fortwo",
      maxPassengers: 2,
      time: [{ per: 1, cost: 0.32 }],
      distance: {
        unit: "km",
        steps: [{ start: 0, end: 200, cost: 0 }, { start: 200, cost: 0.45 }]
      }
    },
    {
      name: "minute rate - mercedes",
      vehicle: "Mercedes Benz CLA/GLA",
      maxPassengers: 5,
      time: [{ per: 1, cost: 0.45 }],
      distance: {
        unit: "km",
        steps: [{ start: 0, end: 200, cost: 0 }, { start: 200, cost: 0.45 }]
      }
    },
   ...
```

> The default calcDefaultCost method should calculate the costs for all packages and sort them.
> 
> So when you say, I want a car for 4 hours and to drive 30 km, it says here are your options:
> Modo - Monthly - Daily Drives - $15.25
> Car2Go - smart - 3 hours - $17.50
> Evo - $18.00
> Car2Go - Mercedes-Benz - 3 hours - $19.25
> Car2Go - smart - 6 hours - $20.00
> Modo - Monthly - Large and Loadable - $21.25

Yes, that's what I was thinking -- a table in the UI. This is just a start.

For a return trip using 1 way car share like Evo, will want to show the stopover option and the 2 trips option.

> If you need a >= 4 passenger vehicle, it can filter out the ones that don't match.

Yes, this will be important for families. I was thinking Mobi could even an option at some point.

**Comment by wachunga** [comment]
Great success:

image

**Comment by wachunga** [comment]
Merging this to keep making progress but we can refactor as needed.

**Pull request merged**
